ad-wizz,http://secunia.com/advisories/43964/
all-in-one-adsense-and-ypn,http://secunia.com/advisories/45579/
category-list-portfolio-page,http://secunia.com/advisories/46088/
conduit-banner-selector,http://secunia.com/advisories/43062/
contact-form-wordpress,http://secunia.com/advisories/46434/
contus-hd-flv-player,http://secunia.com/advisories/45672/
contus-video-galleryversion-10,http://secunia.com/advisories/49494/
dp-thumbnail,http://secunia.com/advisories/46090/
easy-contact-forms-exporter,http://secunia.com/advisories/49450/
events-manager-extended,http://secunia.com/advisories/41294/
featured-content,http://secunia.com/advisories/43064/
feedlist,http://secunia.com/advisories/42197/
fmoblog,http://secunia.com/advisories/34341/
front-file-manager,http://secunia.com/advisories/49428/
grapefile,http://secunia.com/advisories/45719/
hd-webplayer,http://secunia.com/advisories/50466/
html5avmanager,http://secunia.com/advisories/49390/
hungred-post-thumbnail,http://secunia.com/advisories/49447/
invit0r,http://secunia.com/advisories/49519/
is-human,http://secunia.com/advisories/44627/
iwant-one-ihave-one,http://secunia.com/advisories/43467/
kish-guest-posting,http://secunia.com/advisories/47688/
lb-mixed-slideshow,http://secunia.com/advisories/49610/
lim4wp,http://secunia.com/advisories/49609/
lisl-last-image-slider,http://secunia.com/advisories/46108/
meenews,http://secunia.com/advisories/46969/
mm-forms-community,http://secunia.com/advisories/49411/
mz-jajak,http://secunia.com/advisories/50217/
nextgen-smooth-gallery,http://secunia.com/advisories/40858/
odihost-newsletter-plugin,http://secunia.com/advisories/45643/
permalinks-migration-plugin-for-wordpress,http://secunia.com/advisories/28593/
photoracer,http://secunia.com/advisories/35450/
phpfreechat,http://secunia.com/advisories/49826/
pica-photo-gallery,http://secunia.com/advisories/49467/
plugin-newsletter,http://secunia.com/advisories/49464/
quick-post-widget,http://secunia.com/advisories/49798/
register-plus-redux,http://secunia.com/advisories/45503/
register-plus,http://secunia.com/advisories/42360/
rekt-slideshow,http://secunia.com/advisories/46098/
rent-a-car,http://secunia.com/advisories/46100/
rss-feed-reader,http://secunia.com/advisories/43071/
sfbrowser,http://secunia.com/advisories/49466/
simple-download-button-shortcode,http://secunia.com/advisories/49462/
socialfit,http://secunia.com/advisories/49819/
socialgrid,http://secunia.com/advisories/44256/
tagninja,http://secunia.com/advisories/43132/
thinkun-remind,http://secunia.com/advisories/49461/
ucan-post,http://secunia.com/advisories/47656/
upm-polls,http://secunia.com/advisories/47182/
videowhisper-video-presentation,http://secunia.com/advisories/49410/
vk-gallery,http://secunia.com/advisories/46092/
vodpod-video-gallery,http://secunia.com/advisories/42195
wordpress-processing-embed,http://secunia.com/advisories/42545/
wordpress-whois-search,http://secunia.com/advisories/47428/
wp-ajax-recent-posts,http://secunia.com/advisories/44348/
wp-css,http://secunia.com/advisories/45734/
wp-custom-pages,http://secunia.com/advisories/43963/
wp-effective-lead-management,http://secunia.com/advisories/50166/
wp-featured-post-with-thumbnail,http://secunia.com/advisories/43072/
wp-menu-creator,http://secunia.com/advisories/45674/
wp-photo-album,http://secunia.com/advisories/44351/
wp-predict,http://secunia.com/advisories/49843/
wp-safe-search,http://secunia.com/advisories/42544/
wp-simplemail,http://secunia.com/advisories/50208/
wp-starsratebox,http://secunia.com/advisories/44257/
wpeasystats,http://secunia.com/advisories/46069/
wpforum,http://secunia.com/advisories/43552/
x7host-videox7-ugc-plugin,http://secunia.com/advisories/43069/
yahoo-answers-autoposter,http://secunia.com/advisories/48862/
yt-audio-streaming-audio-from-youtube,http://secunia.com/advisories/43539/