ad-wizz,http://secunia.com/advisories/43964/
all-in-one-adsense-and-ypn,http://secunia.com/advisories/45579/
annonces,http://secunia.com/advisories/46070/
audio,http://secunia.com/advisories/43070/
bsuite,http://secunia.com/advisories/45234/
category-list-portfolio-page,http://secunia.com/advisories/46088/
contact-form-wordpress,http://secunia.com/advisories/46434/
contus-hd-flv-player,http://secunia.com/advisories/45672/
dp-thumbnail,http://secunia.com/advisories/46090/
events-manager-extended,http://secunia.com/advisories/41294/
featured-content,http://secunia.com/advisories/43064/
feedlist,http://secunia.com/advisories/42197/
fmoblog,http://secunia.com/advisories/34341/
grapefile,http://secunia.com/advisories/45719/
is-human,http://secunia.com/advisories/44627/
iwant-one-ihave-one,http://secunia.com/advisories/43467/
kish-guest-posting,http://secunia.com/advisories/47688/
lisl-last-image-slider,http://secunia.com/advisories/46108/
meenews,http://secunia.com/advisories/46969/
nextgen-smooth-gallery,http://secunia.com/advisories/40858/
odihost-newsletter-plugin,http://secunia.com/advisories/45643/
onduit-banner-selector,http://secunia.com/advisories/43062/
page-flip-image-gallery,http://secunia.com/advisories/33274/
permalinks-migration-plugin-for-wordpress,http://secunia.com/advisories/28593/
photoracer,http://secunia.com/advisories/35450/
php_speedy_wp,http://secunia.com/advisories/43652/
register-plus-redux,http://secunia.com/advisories/45503/
register-plus,http://secunia.com/advisories/42360/
rekt-slideshow,http://secunia.com/advisories/46098/
rent-a-car,http://secunia.com/advisories/46100/
rss-feed-reader,http://secunia.com/advisories/43071/
seo-automatic-seo-tools,http://secunia.com/advisories/42193/
socialgrid,http://secunia.com/advisories/44256/
tagninja,http://secunia.com/advisories/43132/
ucan-post,http://secunia.com/advisories/47656/
uploader,http://secunia.com/advisories/43075/
upm-polls,http://secunia.com/advisories/47182/
vk-gallery,http://secunia.com/advisories/46092/
vodpod-video-gallery,http://secunia.com/advisories/42195
wordpress-processing-embed,http://secunia.com/advisories/42545/
wordpress-whois-search,http://secunia.com/advisories/47428/
wp-ajax-recent-posts,http://secunia.com/advisories/44348/
wp-css,http://secunia.com/advisories/45734/
wp-custom-pages,http://secunia.com/advisories/43963/
wp-featured-post-with-thumbnail,http://secunia.com/advisories/43072/
wp-menu-creator,http://secunia.com/advisories/45674/
wp-photo-album,http://secunia.com/advisories/44351/
wp-recentcomments,http://secunia.com/advisories/47870/
wp-safe-search,http://secunia.com/advisories/42544/
wp-starsratebox,http://secunia.com/advisories/44257/
wpeasystats,http://secunia.com/advisories/46069/
wpforum,http://secunia.com/advisories/43552/
x7host-videox7-ugc-plugin,http://secunia.com/advisories/43069/
yt-audio-streaming-audio-from-youtube,http://secunia.com/advisories/43539/
zvote,http://secunia.com/advisories/43419/